# Generated by Django 3.1.7 on 2021-04-17 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_customer_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='registerDate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
